### ISSUE TITLE
开启脚本后有一定概率爆显存-8G的4070跑满了，关闭脚本后降到了1.4g

### ISSUE THREAD

**Issue by wang115t** [lazydog28/mc_auto_boss#235]

**Comment by wakening** [comment]
为什么移除我的卡加载监测，是哪里有问题吗

**Comment by wang115t** [comment]
开启游戏后就立马调用的吗

**Comment by wang115t** [comment]
> 为什么移除我的卡加载监测，是哪里有问题吗

是开启游戏就立马调用的吗

**Comment by lazydog28** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/11639

有可能是这个问题

**Comment by wakening** [comment]
> > 为什么移除我的卡加载监测，是哪里有问题吗
> 
> 是开启游戏就立马调用的吗

不是，是执行F5后执行，我已测试过没有任何问题，你若是因为爆内存而注释掉我的代码，可能是你新增代码对图片使用不当导致的，缓存几张图片就会爆，应缓存处理结果，再对结果定时判断。若无问题，请恢复该代码。

**Comment by RoseRin0** [comment]
所以说，尽量调用现有的东西，尽量不要另外加依赖，每一个小功能新写一个文件 还另外开线程，我觉得很离谱反正。
还有，别因为你的原因爆显存让别人别用GPU，GPU在图形处理速度上是远快于CPU的。

**Comment by RoseRin0** [comment]
> [桨桨/桨OCR#11639](https://github.com/PaddlePaddle/PaddleOCR/issues/11639)
> 
> 有可能是这个问题

感觉不像，因为前几天的版本都没有问题，昨天还是今天更新后才出的问题。

**Comment by wakening** [comment]
> 所以说，尽量调用现有的东西，尽量不要另外加依赖，每一个小功能新写一个文件 还另外开线程，我觉得很离谱反正。 还有，别因为你的原因爆显存让别人别用GPU，GPU在图形处理速度上是远快于CPU的。

赞同，最近的版本启动很慢，得卡个半分钟一分钟日志才动

**Comment by wang115t** [comment]
> > > 为什么移除我的卡加载监测，是哪里有问题吗
> > 
> > 
> > 是开启游戏就立马调用的吗
> 
> 不是，是执行F5后执行，我已测试过没有任何问题，你若是因为爆内存而注释掉我的代码，可能是你新增代码对图片使用不当导致的，缓存几张图片就会爆，应缓存处理结果，再对结果定时判断。若无问题，请恢复该代码。

我加了开关，经过测试，关了还是会显存溢出

**Comment by wakening** [comment]
> > > > 为什么移除我的卡加载监测，是哪里有问题吗
> > > 
> > > 
> > > 是开启游戏就立马调用的吗
> > 
> > 
> > 不是，是执行F5后执行，我已测试过没有任何问题，你若是因为爆内存而注释掉我的代码，可能是你新增代码对图片使用不当导致的，缓存几张图片就会爆，应缓存处理结果，再对结果定时判断。若无问题，请恢复该代码。
> 
> 我加了开关，经过测试，关了还是会显存溢出

可以试试将main里新增的那几个进程关掉，并发处理图片容易爆

**Comment by wang115t** [comment]
我怀疑是在切换onnx模型的时候内存泄漏的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月9日(星期二) 凌晨0:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lazydog28/mc_auto_boss] 开启脚本后有一定概率爆显存-8G的4070跑满了，关闭脚本后降到了1.4g (Issue #235)














     
为什么移除我的卡加载监测，是哪里有问题吗
  
是开启游戏就立马调用的吗
  
不是，是执行F5后执行，我已测试过没有任何问题，你若是因为爆内存而注释掉我的代码，可能是你新增代码对图片使用不当导致的，缓存几张图片就会爆，应缓存处理结果，再对结果定时判断。若无问题，请恢复该代码。
  
我加了开关，经过测试，关了还是会显存溢出
  
可以试试将main里新增的那几个进程关掉，并发处理图片容易爆

**Comment by RoseRin0** [comment]
> 我怀疑是在切换onnx模型的时候内存泄漏的问题

你这个也写的很。。。不知道怎么说

```
def check_boss(bossName, is_wait: bool = False):
    """
    根据boss名称判断是否需要等待boss起身

    :param bossName: boss名称
    :param is_wait: 是否需要等待
    """
    bossName = bossName.lower()  # 将bossName转换为小写
    info.resetRole = True

    keywords_turtle = ["鸣", "钟", "之", "龟"]
    keywords_robot = ["聚", "械", "机", "偶"]
    keywords_dreamless = ["无", "妄", "者"]
    keywords_jue = ["角"]
    info.bossTrueName = bossName

    def contains_any_combinations(name, keywords, min_chars):  # 为了防止BOSS名重复，添加了最小匹配关键字数
        for r in range(min_chars, len(keywords) + 1):
            for comb in itertools.combinations(keywords, r):
                if all(word in name for word in comb):
                    return True
        return False
    if contains_any_combinations(bossName, keywords_turtle, min_chars=2):
        info.bossTrueName = "鸣钟之龟"
        info.echoSearchModel = "yolo.onnx"
        wait_time = 16
    elif contains_any_combinations(bossName, keywords_robot, min_chars=2):
        info.bossTrueName = "聚械机偶"
        info.echoSearchModel = "yolo.onnx"
        wait_time = 7
    elif contains_any_combinations(bossName, keywords_dreamless, min_chars=3):
        info.bossTrueName = "无妄者"
        info.echoSearchModel = "heart.onnx"
        wait_time = 4
    elif contains_any_combinations(bossName, keywords_jue, min_chars=1):
        info.bossTrueName = "角"
        info.echoSearchModel = "jue.onnx"
        wait_time = 3
    else:
        info.bossTrueName = bossName
        info.echoSearchModel = "yolo.onnx"
        wait_time = 0

    if is_wait:
        time.sleep(wait_time)
        if wait_time != 0:
            logger(f"{info.bossTrueName}需要等待{wait_time}秒开始战斗！", "DEBUG")
        else:
            logger("当前BOSS不需要等待，直接开始战斗！", "DEBUG")
        logger(f"搜索声骸将调用模型 {info.echoSearchModel}")
        info.waitBoss = False
    else:
        logger(f"即将前往{info.bossTrueName}")
```

本来就有判断BOSS的地方，你要再另外写一个文件出来，重复代码量太多，而且model也就几个文件名改一下，然后在yolo.py里面改一下model_path就完事了，最多加个判断文件存不存在 不存在调用默认的yolo.onnx

`model_path = os.path.join(root_path, "models/" + info.echoSearchModel)`

**Comment by RoseRin0** [comment]
哦 对了 我这切换模型没有任何显存泄露的问题

**Comment by ArcS17** [comment]
爆显存已经严重影响到整个脚本的可用性，希望能好好考虑一下如果找不到问题就回滚到整个ue4崩溃和卡加载部分没有开始影响脚本性能的版本进行重写。
另外，赞同RoseRin0的观点，对这两部分功能的实现并没有必要引入额外依赖添加额外线程，实际上这两个功能导致的报错和脚本性能下降影响已经比其要解决的问题本身还严重了。

**Comment by ss22219** [comment]
有办法解决了吗

**Comment by lazydog28** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/55444285/71bb4d89-888e-4e1a-8cc2-b3a817b68e14)
有尝试过把 配置文件里的`游戏崩溃捕获及处理`部分功能全部关闭嘛？

**Comment by HugoLau91** [comment]
我的4070tis-16G显存都能跑满15G，虽然通过修改OCR.PY禁用GPU而选用CPU会让显存占用降下来（降为3-5G的占用），但是治标不治本，我猜问题就出在OCR的代码上

**Comment by lazydog28** [comment]
> 我的4070tis-16G显存都能跑满15G，虽然通过修改OCR.PY禁用GPU而选用CPU会让显存占用降下来（降为3-5G的占用），但是治标不治本，我猜问题就出在OCR的代码上

你使用的`paddleocr`及`paddlepaddle-gpu`版本各是多少？

**Comment by lazydog28** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/55444285/00b4eb2b-c8e2-4ad7-9c10-1ae9f2bef4cb)

我这边使用的
```
paddleocr              2.7.3
paddlepaddle-gpu       2.6.1.post117
```
正常的GPU内存占用大概是1.5G,峰值大概2.5G

**Comment by HugoLau91** [comment]
> ![image](https://private-user-images.githubusercontent.com/55444285/346844696-00b4eb2b-c8e2-4ad7-9c10-1ae9f2bef4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDg1MzUsIm5iZiI6MTcyMDUwODIzNSwicGF0aCI6Ii81NTQ0NDI4NS8zNDY4NDQ2OTYtMDBiNGViMmItYzhlMi00YWQ3LTljMTAtMWFlOWYyYmVmNGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA2NTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MmVlY2RmOTY3ODdlNzdlOTk3YjJlNWM1MjhhODRiOWI5ZDRjYWRkNmQ0MTJhMzY4MzhiNzQxYTMzY2Y0MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NPbbSZGXkH5QgTNH7_qq8eNXLDnDpiqQ5B2ZcPo6IGs)
> 
> 我这边使用的
> 
> ```
> paddleocr              2.7.3
> paddlepaddle-gpu       2.6.1.post117
> ```
> 
> 正常的GPU内存占用大概是1.5G,峰值大概2.5G

paddleocr              2.8
paddlepaddle-gpu       2.6.1.post117

**Comment by xioaming6023** [comment]
我感觉是寻找BOSS的时候有点问题，进入副本或者开始连招，甚至搜寻声骸都不会爆占用，只有在切换BOSS的时候的图形识别好像格外多，

**Comment by HugoLau91** [comment]
> ![image](https://private-user-images.githubusercontent.com/55444285/346844696-00b4eb2b-c8e2-4ad7-9c10-1ae9f2bef4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTEyMTMsIm5iZiI6MTcyMDUxMDkxMywicGF0aCI6Ii81NTQ0NDI4NS8zNDY4NDQ2OTYtMDBiNGViMmItYzhlMi00YWQ3LTljMTAtMWFlOWYyYmVmNGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA3NDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZmVkODAwNTJlZjQ0MjQ1MTI3NjRmMGRiMDc5ZmFkMDc4NTI4OWM1NTdhOWQzN2RiNjc2YTczNzBjNTc0MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWPiZlA0dXX5oVlC09Vn2pou3qN1pO4-AvOSLCoStcM)
> 
> 我这边使用的
> 
> ```
> paddleocr              2.7.3
> paddlepaddle-gpu       2.6.1.post117
> ```
> 
> 正常的GPU内存占用大概是1.5G,峰值大概2.5G

ocr.py调用GPU情况下的显存占用情况，最高峰值15.5G
![内存占用](https://github.com/lazydog28/mc_auto_boss/assets/148528479/13214a7c-44b6-46e9-afd9-b2e51273635c)
![内存占用2](https://github.com/lazydog28/mc_auto_boss/assets/148528479/2d79abcf-f7a4-4275-abd2-127d3790128e)

**Comment by lazydog28** [comment]
> > ![image](https://private-user-images.githubusercontent.com/55444285/346844696-00b4eb2b-c8e2-4ad7-9c10-1ae9f2bef4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTEyMTMsIm5iZiI6MTcyMDUxMDkxMywicGF0aCI6Ii81NTQ0NDI4NS8zNDY4NDQ2OTYtMDBiNGViMmItYzhlMi00YWQ3LTljMTAtMWFlOWYyYmVmNGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA3NDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZmVkODAwNTJlZjQ0MjQ1MTI3NjRmMGRiMDc5ZmFkMDc4NTI4OWM1NTdhOWQzN2RiNjc2YTczNzBjNTc0MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWPiZlA0dXX5oVlC09Vn2pou3qN1pO4-AvOSLCoStcM)
> > 我这边使用的
> > ```
> > paddleocr              2.7.3
> > paddlepaddle-gpu       2.6.1.post117
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 正常的GPU内存占用大概是1.5G,峰值大概2.5G
> 
> ocr.py调用GPU情况下的显存占用情况，最高峰值15.5G ![内存占用](https://private-user-images.githubusercontent.com/148528479/346870424-13214a7c-44b6-46e9-afd9-b2e51273635c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTk1MjYsIm5iZiI6MTcyMDUxOTIyNiwicGF0aCI6Ii8xNDg1Mjg0NzkvMzQ2ODcwNDI0LTEzMjE0YTdjLTQ0YjYtNDZlOS1hZmQ5LWIyZTUxMjczNjM1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMDAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWEwN2M3MmE4MjM1ZDQ4OGViYmFlODJkMDFjMmI2YmRiMWEzMDM0YWI2NDliNTMwMjgzOTUyNTg5MjlmNGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6PEwZJ0FFXndz55fXxm8HAhkgrfpStBsvu9i4RbXJYk) ![内存占用2](https://private-user-images.githubusercontent.com/148528479/346870512-2d79abcf-f7a4-4275-abd2-127d3790128e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTk1MjYsIm5iZiI6MTcyMDUxOTIyNiwicGF0aCI6Ii8xNDg1Mjg0NzkvMzQ2ODcwNTEyLTJkNzlhYmNmLWY3YTQtNDI3NS1hYmQyLTEyN2QzNzkwMTI4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMDAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTFmOGYwNTFlN2RjZDJiMzJmMjEwMDhmMjk4YzY5ZmJmNzM5ZDEyOTU3NDY1ZDlmYTcxNjc4MjUxMDA4YzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G0p6aO7f7xXd17kW5628UKlycOdpA9KARqO9PjXGoK0)

用任务管理器，详细信息，在列名的地方右键后选择列，显示 `专用GPU内存`，然后按照专用GPU内存列，倒序排序。看具体是哪个进程占用

**Comment by lazydog28** [comment]
> paddleocr 2.8

试试 paddleocr 2.8 换成 paddleocr 2.7.3

**Comment by lazydog28** [comment]
https://github.com/lazydog28/mc_auto_boss/issues/242#issue-2397930946

```
另外win11 40系显卡(30系不知道没测试)用Client-Win64-Shipping.exe启动建议添加-dx11参数,
因为在win11系统下40显卡用Client-Win64-Shipping.exe启动游戏默认走的是dx12
dx12没有锁帧也没优化显存会无限增加不会释放,多少都不够用,之前Xbox启动解锁120也是这个原理
```

**Comment by HugoLau91** [comment]
> > paddleocr 2.8
> 
> 试试 paddleocr 2.8 换成 paddleocr 2.7.3

已更换paddleocr 2.7.3，使用GPU运算，脚本v.1.2.3，没有之前的爆显存情况，目前战斗最高占用大概是6G显存，最新测试结果如图，不清楚是paddleocr版本问题还是1.2.3的脚本优化了，还有使用了-dx11指令：
![22222222](https://github.com/lazydog28/mc_auto_boss/assets/148528479/b1204259-31a8-42b5-b43f-dee41dfab465)

**Comment by Chris-Mraz** [comment]
> > paddleocr 2.8
> 
> 试试 paddleocr 2.8 换成 paddleocr 2.7.3

这个确实，好像解决了，赞
