### ISSUE TITLE
请问大佬这个是什么问题，到搜索声骸就崩溃

### ISSUE THREAD

**Issue by wubinhuaheheda** [lazydog28/mc_auto_boss#55]
![Uploading B$}1T_%RZDOP[R9C2%LW4GK.png…]()

**Comment by wubinhuaheheda** [comment]
![Uploading B$}1T_%RZDOP[R9C2%LW4GK.png…]()

**Comment by wubinhuaheheda** [comment]
图不知道为什么上传不了..
2024-06-08 23:35:21 战斗次数：1 吸收次数：0 当前条件操作：搜索声骸2024-06-08 23:35:23.0282500 [E:onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/model.12/cv1/conv/Conv' Status Message: C:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:123 onnxruntime::CudaCall C:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:116 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-LJNMVTP ; file=C:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_allocator.cc ; line=47 ; expr=cudaMalloc((void**)&p, size);


Process task:
Traceback (most recent call last):
  File "C:\Users\adminsitrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\adminsitrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\adminsitrator\Desktop\mc_auto_boss-gpu\background\main.py", line 32, in run
    task(img, result)
  File "C:\Users\adminsitrator\Desktop\mc_auto_boss-gpu\background\schema.py", line 276, in __call__
    conditionalAction.action()
  File "C:\Users\adminsitrator\Desktop\mc_auto_boss-gpu\background\task\conditional_actions\boss.py", line 18, in judgment_absorption_action
    absorption_action()
  File "C:\Users\adminsitrator\Desktop\mc_auto_boss-gpu\background\utils.py", line 376, in absorption_action
    x = turn_to_search()
  File "C:\Users\adminsitrator\Desktop\mc_auto_boss-gpu\background\utils.py", line 361, in turn_to_search
    x = search_echoes(img)
  File "C:\Users\adminsitrator\Desktop\mc_auto_boss-gpu\background\yolo.py", line 237, in search_echoes
    pred = model.run([label_name], {input_name: im})
  File "C:\Users\adminsitrator\AppData\Roaming\Python\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Conv node. Name:'/model.12/cv1/conv/Conv' Status Message: C:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:123 onnxruntime::CudaCall C:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:116 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-LJNMVTP ; file=C:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_allocator.cc ; line=47 ; expr=cudaMalloc((void**)&p, size);

**Comment by lazydog28** [comment]
内存不足

**Comment by wubinhuaheheda** [comment]
> 内存不足

感谢，已解决
